### ISSUE TITLE
Running tests outside /system folder

### ISSUE THREAD

**Issue by omsoft** [ledermann/pingcrm#1638]
I would like to add a simple `test/models/my_model_test.rb` to run "standard" tests (without Capybara) but they fail with error:

```
    messages = page.driver.browser.manage.logs.get(:browser).
               ^^^^
    test/test_helper.rb:15:in `block in <class:TestCase>'
```

This is because test_helper.rb calls teardown block. Is there an easy way to baypass it?

**Comment by ledermann** [comment]
This project is not a good example for setting up a test suite. 
Nevertheless, you are right, the `test_helper.rb` includes code which only belongs to system tests. I fixed this. 

Thanks for this hint!
